modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/CamoCreepers/issues"
license="MIT"

[[mods]]
modId="camocreepers"
version="${file.jarVersion}"
displayName="Camo Creepers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/camo-creepers"
authors="Mrbysco"
description='''
Creepers that blend in more with the environment
'''
[[dependencies.camocreepers]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.camocreepers]]
modId="neoforge"
mandatory=true
versionRange="[20.2.59-beta,)"
ordering="NONE"
side="BOTH"