modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Mrbysco/CamoCreepers"
license="MIT"

[[mods]]
modId="camocreepers"
version="${file.jarVersion}"
displayName="Camo Creepers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/camo-creepers"
authors="Mrbysco"
description='''
Creepers that blend in more with the environment
'''
[[dependencies.camocreepers]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
[[dependencies.camocreepers]]
modId="forge"
mandatory=true
versionRange="[36.2.17,)"
ordering="NONE"
side="BOTH"