modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/CamoCreepers/issues"
license="MIT"

[[mods]]
modId="camocreepers"
version="${file.jarVersion}"
displayName="Camo Creepers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/camo-creepers"
authors="Mrbysco"
description='''
Creepers that blend in more with the environment
'''
[[dependencies.camocreepers]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.camocreepers]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.60-beta,)"
ordering="NONE"
side="BOTH"