modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Mrbysco/CamoCreepers/issues"
license="MIT"

[[mods]]
modId="camocreepers"
version="${file.jarVersion}"
displayName="Camo Creepers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/camo-creepers"
authors="Mrbysco"
description='''
Creepers that blend in more with the environment
'''
[[dependencies.camocreepers]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"